apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260619-145120-cgke07rdgwdh-service
spec:
  selector:
    app: enterprise-system-20260619-145120-cgke07rdgwdh
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
